-- Script to update schema for Module-Based Architecture
-- Warning: This will wipe existing courses and related data to apply the new hierarchy cleanly.
TRUNCATE TABLE courses CASCADE;

-- 1. Create modules table
CREATE TABLE IF NOT EXISTS modules (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id integer NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  title varchar(500) NOT NULL,
  description text,
  sort_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 2. Modify lessons table
-- Since the table is truncated via CASCADE, we can safely drop and add columns.
ALTER TABLE lessons DROP COLUMN IF EXISTS course_id CASCADE;
ALTER TABLE lessons ADD COLUMN module_id integer NOT NULL REFERENCES modules(id) ON DELETE CASCADE;

-- 3. Create materials table for PDFs
CREATE TABLE IF NOT EXISTS materials (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id integer NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
  title varchar(500) NOT NULL,
  file_url text NOT NULL,
  sort_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

-- 4. Modify quizzes table
ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS module_id integer REFERENCES modules(id) ON DELETE CASCADE;
-- If module_id is NULL, it is the final end-of-course quiz.
ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS quiz_type varchar(20) DEFAULT 'module';

-- 5. Create user_progress tracking for individual video lessons
CREATE TABLE IF NOT EXISTS lesson_progress (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  lesson_id integer NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  completed boolean DEFAULT FALSE,
  completed_at timestamptz,
  UNIQUE(user_id, lesson_id)
);

-- 6. Expand quiz_questions to support denormalized fields for AI quiz generator
ALTER TABLE quiz_questions ADD COLUMN IF NOT EXISTS course_id integer;
ALTER TABLE quiz_questions ADD COLUMN IF NOT EXISTS module_id integer;
ALTER TABLE quiz_questions ADD COLUMN IF NOT EXISTS quiz_type varchar(20);
ALTER TABLE quiz_questions ADD COLUMN IF NOT EXISTS option_a text;
ALTER TABLE quiz_questions ADD COLUMN IF NOT EXISTS option_b text;
ALTER TABLE quiz_questions ADD COLUMN IF NOT EXISTS option_c text;
ALTER TABLE quiz_questions ADD COLUMN IF NOT EXISTS option_d text;
ALTER TABLE quiz_questions ADD COLUMN IF NOT EXISTS correct_answer varchar(1);

-- Note: We already have an assessments table for quiz attempts which works well.
-- `enrollments` table handles overall course progress and completion status.
